blank_issues_enabled: true
contact_links:
  - name: Contribution guidelines / 贡献指南
    url: https://github.com/SudoAI-DEV/awesome-chess/blob/main/CONTRIBUTING.md
    about: Please read this before suggesting a resource. / 推荐资源前请先阅读。
